def create_base_txt():
    """BVE 기본 구문 템플릿"""
    base_txt = ''
    base_txt += 'Options.ObjectVisibility 1\n'
    base_txt += 'With Route\n'
    base_txt += '.comment 세그먼트컬렉션 테스트루트\n'
    base_txt += '.Elevation 0\n'
    base_txt += 'With Train\n'
    base_txt += 'With Structure\n'
    base_txt += '$Include(오브젝트.txt)\n'
    base_txt += '$Include(프리오브젝트.txt)\n'
    base_txt += '$Include(km_index.txt)\n'
    base_txt += '$Include(curve_index.txt)\n'
    base_txt += '$Include(pitch_index.txt)\n'
    base_txt += 'With Track\n'
    base_txt += '$Include(전주.txt)\n'
    base_txt += '$Include(전차선.txt)\n'
    base_txt += '$Include(km_post.txt)\n'
    base_txt += '$Include(curve_post.txt)\n'
    base_txt += '$Include(pitch_post.txt)\n'
    base_txt += '$Include(신호.txt)\n'
    base_txt += '$Include(통신.txt)\n'
    base_txt += '0,.back 0;,.ground 0;,.dike 0;0;2;,.railtype 0;9;\n'
    base_txt += '0,.sta START STATION;\n'
    base_txt += '100,.stop 0;\n'
    return base_txt